// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ehealthwatch-homepage/BoldScience.tsx": () => import("../components/mockups/ehealthwatch-homepage/BoldScience.tsx"),
  "./components/mockups/ehealthwatch-homepage/ClinicalTrust.tsx": () => import("../components/mockups/ehealthwatch-homepage/ClinicalTrust.tsx"),
  "./components/mockups/ehealthwatch-homepage/WarmWellness.tsx": () => import("../components/mockups/ehealthwatch-homepage/WarmWellness.tsx")
};
